name: Compilar App Android

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Limpiar y Configurar NuGet
      run: |
        dotnet nuget locals all --clear
        dotnet workload install maui-android

    - name: Publicar APK
      run: |
        dotnet publish EtiquetadoAuto.csproj \
          -f net8.0-android \
          -c Release \
          -p:AndroidKeyStore=false \
          -p:CheckEolTargetFramework=false \
          -p:NoWarn=NETSDK1202 \
          --source https://api.nuget.org/v3/index.json